exports.downloader = require('./downloader')
exports.meme = require('./meme')
exports.removebg = require('./remove-bg')
exports.urlShortener = require('./shortener')
exports.translate = require('./translate')
exports.covid = require('./covid')
exports.live = require('./live')